steps:
  #  Build
  - name: 'maven'
    args: [ './mvnw', 'package' ]
    id: Build
  #  Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - vacation-worker-function
      - --entry-point=org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
      - --region=europe-west3
      - --source=target/deploy
      - --trigger-http
      - --runtime=java17
      - --memory=512MB
      - --timeout=90
      - --min-instances=0
      - --max-instances=1
      - --allow-unauthenticated
      - --service-account=vacation-worker-function@vacation-worker-project.iam.gserviceaccount.com
      - --quiet
    id: Deploy